### Login page
GET http://localhost:8080/login

# this is code for saving csrf Token to a global var. Fetch a csrf token from the login page or create an endpoint
# > {% client.global.set("csrfToken", response.body.match('<input name="_csrf" type="hidden" value="(.*?)"')[1]); %}
# If use of csrf just add to the form below &_csrf={{csrfToken}}

### Perform login with the CSRF token
POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded

username=user&password=64aa06c5-aa11-47f6-b959-fb940ec071b2

### Create a users
POST http://localhost:8080/users
Content-Type: application/json
X-CSRF-Token: {{csrfToken}}

 { "nickname": "shishi",
   "name": "delyan",
   "lastname": "peevski",
   "email": "delyancho@praseto.com"}

### Get the users
GET http://localhost:8080/users


